#!/bin/bash


calculate_area() {
    local radius=$1
    local area=$(echo "3.14159 * $radius * $radius" | bc)
    echo "The area of the circle with radius $radius is: $area"
}


read -p "Enter the radius of the circle: " radius


calculate_area "$radius"

  ----------------------------------------------------------------------------------------------

output:

Enter the radius of the circle: 4
The area of the circle with radius 4 is: 50.26544

  
