#!/bin/bash


echo "Enter value for a:"
read a

echo "Enter value for b:"
read b

echo "Enter value for c:"
read c

echo "Enter value for d:"
read d


result=$(echo "scale=2; ($a * 20) - ($b * 2) + ($c / $d)" | bc)


echo "Result: $result"

~                                

---------------------------------------------------------------------------------

output:


Enter value for a:
5
Enter value for b:
2
Enter value for c:
4
Enter value for d:
1
Result: 100.00
